"""The report: the presence bar, section 8's prose, and the worked example in PLANNER.md.

    python3 tests/test_plan_report.py

report.py's own docstring says the module exists for the ASCII presence bar -- "a table
hides co-residency ... the one quantity this planner is about is a relation between rows,
and no column shows it" -- and nothing asserted a column of it. Replacing the productive
test with `if False` left every other plan test green while the bar showed nobody
training and the federated row came out empty.

So the bar is checked COLUMN BY COLUMN against hand-computed hours here, not by asking
whether each glyph appears somewhere. The three ways it can lie are all position bugs:
drawing `#` from arrival instead of from productive (which hides c, the startup a chain
re-pays per link), drawing `#` past the run end (which hides the hours billed after the
corpus is gone), and deriving `^` from lanes rather than sites (which turns one site's
two Flower clients into a federated round that never happened).

The last four checks are about PLANNER.md rather than about code. Its worked example is
pasted output, and it drifted from the tool in the flattering direction: it quoted 18.2 M
tokens/GPU-h against the tool's 7.81 M after GPU-hours began counting the held
allocation. A doc regenerated by hand needs a test, or it is a comment.
"""

from __future__ import annotations

import contextlib
import dataclasses
import io
import os
import re
import signal
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

PASSED, FAILED = [], []
CHECK_TIMEOUT_S = 120


def check(name: str):
    def decorator(fn):
        def on_timeout(signum, frame):
            raise TimeoutError(f"exceeded {CHECK_TIMEOUT_S}s")

        previous = signal.signal(signal.SIGALRM, on_timeout)
        signal.alarm(CHECK_TIMEOUT_S)
        try:
            fn()
            PASSED.append(name)
            print(f"  PASS  {name}")
        except Exception as exc:  # noqa: BLE001
            FAILED.append((name, exc))
            print(f"  FAIL  {name}: {type(exc).__name__}: {exc}")
        finally:
            signal.alarm(0)
            signal.signal(signal.SIGALRM, previous)
        return fn

    return decorator


from pww.plan import (  # noqa: E402
    DEFAULT_CALIBRATION as CAL,
    DarlState,
    Geometry,
    PlanConfig,
    PlannerInputs,
    Shape,
    SiteInput,
    WaitEstimate,
    make_plan,
)
from pww.plan import report as report_mod  # noqa: E402
from pww.plan.adapter import Collected  # noqa: E402
from pww.plan.inputs import parse_shape_args  # noqa: E402
from pww.plan.model import Link  # noqa: E402

HOUR = 3600.0
PLANNER_MD = ROOT / "PLANNER.md"
MID_RUN = DarlState(num_blocks=2692, committed=1870, leased=0, unassigned=822,
                    source="http://145.38.206.143:29510", observed=True)


def site_input(name: str, partition: str, gpus: int, tput: float, batch: int,
               wait_h: float, *, used_ratio: float | None = None) -> SiteInput:
    args = f"-p {partition} -N 1 --gpus-per-node {gpus} -t 8:00:00"
    shape = Shape(f"{name}_{gpus}g_8h", parse_shape_args(name, args), args)
    wait = WaitEstimate(p50_raw_s=wait_h * HOUR, p90_raw_s=wait_h * HOUR,
                        p50_eff_s=wait_h * HOUR, p90_eff_s=wait_h * HOUR,
                        samples=3, probe_age_s=60.0, used_ratio=used_ratio)
    return SiteInput(site=name, shapes=(shape,), waits={shape.name: wait},
                     geometries={gpus: Geometry(name, gpus, tput, batch)},
                     startup_s=300.0)


SITES = (site_input("snellius", "gpu_h100", 4, 89.8, 32, 0.0),
         site_input("lumi", "standard-g", 8, 38.2, 64, 2.0))
# One search, reused: the bar checks replace the timeline wholesale, so what this plan
# selected does not matter -- only that it is a real Plan with a real PlanConfig on it.
BASE = make_plan(PlannerInputs(sites=SITES, calibration=CAL, darl=MID_RUN),
                 PlanConfig(horizon_s=24 * HOUR, num_rounds=1_000_000, lanes_max=1,
                            assume_overhead=True))
COLLECTED = Collected(inputs=PlannerInputs(sites=SITES, calibration=CAL, darl=MID_RUN),
                      provenance=(), notes=(), raw={})


def link(site: str, lane: str, submit_h: float, arrival_h: float, productive_h: float,
         end_h: float) -> Link:
    return Link(lane_id=lane, site=site, index=0, submit_s=submit_h * HOUR,
                arrival_s=arrival_h * HOUR, productive_s=productive_h * HOUR,
                end_s=end_h * HOUR, cold=True, walltime_s=(end_h - arrival_h) * HOUR)


def bars(links, *, run_end_h: float, horizon_h: float, width: int) -> list[str]:
    plan = dataclasses.replace(
        BASE,
        config=dataclasses.replace(BASE.config, horizon_s=horizon_h * HOUR),
        timeline=dataclasses.replace(BASE.timeline, links=tuple(links),
                                     run_end_s=run_end_h * HOUR))
    return report_mod.presence_bars(plan, width=width)


def rows_of(lines) -> dict[str, str]:
    return {line.split("|")[0].strip(): line.split("|")[1] for line in lines if "|" in line}


# --------------------------------------------------------------------------
# the presence bar
# --------------------------------------------------------------------------


@check("every glyph of the presence bar lands in the column whose cost it names")
def _():
    """12 columns over a 12 h axis, so column k is sampled at k+0.5 h and every glyph is
    hand-computable. The four states are four different bills: `~` queued is free, `:` is
    allocated-but-starting-up (billed, contributing nothing -- this is c, and it is why
    chaining is not free), `#` is productive, `.` is absent."""
    rows = rows_of(bars(
        [link("snellius", "snellius-l0", 0.0, 2.0, 3.0, 10.0),
         link("lumi", "lumi-l0", 0.0, 5.0, 6.0, 12.0)],
        run_end_h=9.0, horizon_h=12.0, width=12))
    #                          hour 0123456789..
    assert rows["snellius"] == "~~:######...", rows["snellius"]
    assert rows["lumi"] == "~~~~~:###...", rows["lumi"]
    assert rows["federated"] == "      ^^^   ", repr(rows["federated"])
    assert len({len(v) for v in rows.values()}) == 1, {k: len(v) for k, v in rows.items()}
    assert set("".join(rows.values())) <= set(".~:#^ "), set("".join(rows.values()))


@check("`#` stops when the RUN ends, not when the walltime does")
def _():
    """The jobs outlive the corpus -- the client does not exit when DARL is exhausted --
    and on the live plan that is 126 of 221 GPU-h billed after there is anything left to
    train on. A bar clipped at end_s instead of run_end_s draws those hours as productive,
    which is the reading of this report that costs an allocation."""
    links = [link("snellius", "snellius-l0", 0.0, 0.0, 0.0, 12.0)]
    lines = bars(links, run_end_h=6.0, horizon_h=12.0, width=12)
    assert rows_of(lines)["snellius"] == "######......", rows_of(lines)
    assert any("the run ENDED at 6.0 h" in line for line in lines), lines
    # ... and when the run fills the axis there is nothing to warn about
    full = bars(links, run_end_h=12.0, horizon_h=12.0, width=12)
    assert rows_of(full)["snellius"] == "############", rows_of(full)
    assert not any("the run ENDED" in line for line in full), full


@check("the federated row counts SITES, not lanes")
def _():
    """Two lanes at one site are two Flower clients and the server does merge them, but
    they share the hardware, the queue, the WAN link and the failure -- that is not the
    measurement this campaign makes."""
    rows = rows_of(bars(
        [link("snellius", "snellius-l0", 0.0, 0.0, 0.0, 12.0),
         link("snellius", "snellius-l1", 0.0, 0.0, 0.0, 12.0)],
        run_end_h=12.0, horizon_h=12.0, width=12))
    assert rows["snellius"] == "############", rows["snellius"]
    assert rows["federated"].strip() == "", repr(rows["federated"])
    # a second SITE, present for exactly half the axis, does produce them
    rows = rows_of(bars(
        [link("snellius", "snellius-l0", 0.0, 0.0, 0.0, 12.0),
         link("snellius", "snellius-l1", 0.0, 0.0, 0.0, 12.0),
         link("lumi", "lumi-l0", 0.0, 6.0, 6.0, 12.0)],
        run_end_h=12.0, horizon_h=12.0, width=12))
    assert rows["federated"] == "      ^^^^^^", repr(rows["federated"])


@check("the bar reaches the reader: printed in section 3, carried in --json")
def _():
    """presence_bars() being right is worth nothing if render() stops calling it, and the
    --json consumer must get the same artifact rather than a table to re-derive it from."""
    text = report_mod.render(BASE, COLLECTED, (), CAL)
    section3 = text[text.index("3. TIMELINE"):text.index("4. PER-SITE LEDGER")]
    drawn = report_mod.presence_bars(BASE)
    assert len(rows_of(drawn)) >= 2, drawn
    for line in drawn:
        assert line in section3, line
    tree = report_mod.as_json(BASE, COLLECTED, (), CAL)
    assert tree["derived"]["presence_bars"] == drawn, tree["derived"]["presence_bars"]


# --------------------------------------------------------------------------
# section 8, the last thing read before an allocation is spent
# --------------------------------------------------------------------------


@check("section 8 quotes the used_ratio of the shapes THIS plan chose")
def _():
    """It used to read "used_ratio on Snellius gpu_h100 is ~0.11 ... finished jobs
    consumed 11% of what they asked for" while section 1 of the same report printed
    0.1617 for that partition. The ratio is the whole argument for reading the quoted
    wait as pessimistic, and it is the input to w_eff = w*(1 - s*(1 - used_ratio)): a
    literal in the prose disagrees with the arithmetic the plan was priced with."""
    sites = (site_input("snellius", "gpu_h100", 4, 89.8, 32, 0.0, used_ratio=0.4242),
             site_input("lumi", "standard-g", 8, 38.2, 64, 2.0, used_ratio=0.3131))
    collected = Collected(
        inputs=PlannerInputs(sites=sites, calibration=CAL, darl=MID_RUN),
        provenance=(), notes=(), raw={})
    plan = make_plan(collected.inputs, BASE.config)
    text = report_mod.render(plan, collected, (), CAL)
    section8 = text[text.index("8. SBATCH"):]
    assert "0.11" not in section8 and "11%" not in section8, section8[:900]
    chosen = {o.site for o in plan.selection}
    assert chosen, plan.describe()
    for site in sites:
        ratio = next(iter(site.waits.values())).used_ratio
        assert (f"{ratio:.4f}" in section8) == (site.site in chosen), (site.site, section8)


@check("section 8 says the discount did NOT fire when no usage row was read")
def _():
    """The discount silently no-ops on a null used_ratio, so a plan reads as discounted
    when it is not. Section 8 is where an operator decides whether to trust the quoted
    wait, so that branch has to say so rather than print nothing."""
    assert all(w.used_ratio is None for s in SITES for w in s.waits.values())
    text = report_mod.render(BASE, COLLECTED, (), CAL)
    section8 = text[text.index("8. SBATCH"):]
    assert "no usage row was found" in section8, section8[:900]
    assert "NOT fire" in section8, section8[:900]
    assert "Measured used_ratio" not in section8, section8[:900]


# --------------------------------------------------------------------------
# PLANNER.md's worked example is pasted output, and stays that way
# --------------------------------------------------------------------------


def _worked_example_blocks() -> tuple[str, list[str]]:
    """The fenced blocks of PLANNER.md's "Reading the output" section.

    ```bash``` is the command that regenerates the section; a bare ``` fence is pasted
    output. Inside output, a line of `...` is a dropped line and a line ending in `...`
    is quoted to its first words only -- both because the report is 78 columns wide and
    the interval table is 18 rows.
    """
    text = PLANNER_MD.read_text()
    start = text.index("## Reading the output")
    section = text[start:text.index("\n## ", start + 1)]
    command, quoted, fence = "", [], None
    for line in section.split("\n"):
        if line.startswith("```"):
            fence = None if fence is not None else (line[3:].strip() or "output")
            continue
        if fence == "bash":
            command += line
        elif fence == "output" and line.strip():
            quoted.append(line.rstrip())
    return command, quoted


_OUTPUT: list[str] = []


def documented_run() -> list[str]:
    """Run the command PLANNER.md tells the reader to run, from the checkout root.

    Once, and shared: the search is exact over 221 selections and the sensitivity sweep
    re-solves it 17 times, which is ~2 s -- more than the rest of this file put together.
    """
    if not _OUTPUT:
        from pww.plan import cli

        command, _ = _worked_example_blocks()
        fixture = re.search(r"--dry-run (\S+)", command).group(1)
        assert (ROOT / fixture).exists(), fixture
        out, cwd = io.StringIO(), os.getcwd()
        os.chdir(ROOT)                  # the documented command is run from the checkout
        try:
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(io.StringIO()):
                cli.main(["--dry-run", fixture])
        finally:
            os.chdir(cwd)
        _OUTPUT.extend(line.rstrip() for line in out.getvalue().split("\n"))
    return _OUTPUT


@check("PLANNER.md's worked example is what the tool prints today")
def _():
    """The example is pasted output and every repair pass has edited it by hand instead:
    it quoted 95 GPU-h and 18.2 M tokens/GPU-h -- the accounting from before GPU-hours
    counted the held allocation -- against the tool's 220.6 and 7.81 M, while U, fed,
    solo, tokens and alpha* still matched, which makes a wrong number harder to notice,
    not easier. tokens/GPU-h is reported and never optimised, so nothing else in the plan
    contradicts a stale one."""
    command, quoted = _worked_example_blocks()
    assert "python3 -m pww.plan" in command and "--dry-run" in command, command
    assert len(quoted) > 20, len(quoted)
    printed = documented_run()
    stripped = {line.strip() for line in printed}
    stale = (f"PLANNER.md quotes a line the tool no longer prints: %r. Regenerate the "
             f"section with: {command.strip()}")

    for line in quoted:
        want = line.strip()
        if want == "...":
            continue
        if want.endswith("..."):
            assert any(l.strip().startswith(want[:-3]) for l in printed), stale % want
        else:
            assert want in stripped, stale % want


@check("PLANNER.md's p50/p90 paragraph is the sensitivity table's answer")
def _():
    """The doc said "at p90 the recommendation is again Snellius alone" while the sweep
    kept both sites at p90 and the report printed no w-FRAGILE block. That paragraph is
    the one that tells a reader whether the plan is a bet on the median, so it has to
    move with the sweep rather than describe some earlier queue."""
    rows = {}
    for line in documented_run():
        parts = line.split()
        if len(parts) > 5 and parts[0] == "wait_quantile":
            rows[parts[1]] = (parts[2], parts[3], " ".join(parts[5:]))
    assert set(rows) == {"p50", "p90"}, rows
    fragile = rows["p50"][2] != rows["p90"][2]
    assert fragile == any("w-FRAGILE" in l for l in documented_run()), rows

    text = PLANNER_MD.read_text()
    section = text[text.index("## The two ways the wait estimate is wrong"):]
    section = section[:section.index("\n## ")]
    if fragile:
        assert "fragile" in section.lower(), section[-600:]
    else:
        utility, federated, _ = rows["p90"]
        assert utility in section and federated in section, (rows["p90"], section[-600:])


@check("PLANNER.md quotes no frozen test total")
def _():
    """It said "100 checks" against 103 in the four files, and the four files gain checks
    every time this planner is reviewed. A total nobody can keep current is a defect with
    a shelf life, so the doc names the runner and each file prints its own count."""
    status = PLANNER_MD.read_text()
    status = status[status.index("## Status"):]
    assert 'for t in tests/test_plan_*.py' in status, status[:600]
    assert not re.search(r"\b\d+ checks\b", status), \
        "a check total written here is stale the next time anyone adds one"


@check("PLANNER.md's block-to-token conversion is the calibration's, not a typo")
def _():
    """The doc said one block is 2,098,176 tokens, which is 1024*2049. It is the only
    statement of the conversion on that page and every merge count in the arithmetic
    section is derived through it."""
    assert (CAL.block_size, CAL.seq_len) == (1024, 2048), (CAL.block_size, CAL.seq_len)
    tokens = CAL.block_size * CAL.seq_len
    text = PLANNER_MD.read_text()
    line = next(l for l in text.split("\n") if l.startswith("**Data.** One block"))
    assert f"{tokens:,} tokens" in line, (line, tokens)
    assert "2,098,176" not in text, "1024*2049 is back"


def main() -> int:
    print()
    print(f"{len(PASSED)} passed, {len(FAILED)} failed")
    for name, exc in FAILED:
        print(f"  {name}: {type(exc).__name__}: {exc}")
    return 1 if FAILED else 0


if __name__ == "__main__":
    sys.exit(main())
